import 'gpu_instance.dart';

/// Describes the player's current mining farm.
class Farm {
  final List<GpuInstance> gpuList;
  final int totalSlots;
  final String coolingSystem; // 'basic', 'fans', 'water', 'immersion'
  final double solarPower; // watts generated by solar panels

  const Farm({
    required this.gpuList,
    required this.totalSlots,
    this.coolingSystem = 'basic',
    this.solarPower = 0,
  });

  int get usedSlots => gpuList.length;
  bool get hasFreeSlots => usedSlots < totalSlots;

  Farm copyWith({
    List<GpuInstance>? gpuList,
    int? totalSlots,
    String? coolingSystem,
    double? solarPower,
  }) {
    return Farm(
      gpuList: gpuList ?? this.gpuList,
      totalSlots: totalSlots ?? this.totalSlots,
      coolingSystem: coolingSystem ?? this.coolingSystem,
      solarPower: solarPower ?? this.solarPower,
    );
  }
}
