import 'gpu_instance.dart';

/// Describes the player's current mining farm.
class Farm {
  final List<GpuInstance> gpuList;
  final int totalSlots;
  final String coolingSystem; // 'basic', 'fans', 'water', 'immersion'
  final double solarPower; // watts generated by solar panels
  final String psuTier; // 'psu_stock', 'psu_bronze', 'psu_gold'

  const Farm({
    required this.gpuList,
    required this.totalSlots,
    this.coolingSystem = 'basic',
    this.solarPower = 0,
    this.psuTier = 'psu_stock',
  });

  int get usedSlots => gpuList.length;
  bool get hasFreeSlots => usedSlots < totalSlots;

  Farm copyWith({
    List<GpuInstance>? gpuList,
    int? totalSlots,
    String? coolingSystem,
    double? solarPower,
    String? psuTier,
  }) {
    return Farm(
      gpuList: gpuList ?? this.gpuList,
      totalSlots: totalSlots ?? this.totalSlots,
      coolingSystem: coolingSystem ?? this.coolingSystem,
      solarPower: solarPower ?? this.solarPower,
      psuTier: psuTier ?? this.psuTier,
    );
  }
}
